---
services:
  backup-container:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/backup/source1:ro
      - ./rclone:/root/.config/rclone
    env_file: .env
    environment:
      - TZ=Europe/Berlin